(function(){
  const VAPID_PUBLIC_KEY='BFRUDmv_I4zXzDcjLgaVsynZ-UjAuLQ1ihC-DmfOePAOSjIHmlHlzpdlsCWxpBjormzPQTw8Mh_SWPnV6NwXosI';
  const DEVICE_KEY='171-timesheet-device-id';
  function bytes(base64){const pad='='.repeat((4-base64.length%4)%4);const raw=atob((base64+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
  function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
  function css(){if(document.getElementById('notificationCss'))return;const l=document.createElement('link');l.id='notificationCss';l.rel='stylesheet';l.href=`notifications.css?v=${Date.now()}`;document.head.appendChild(l)}
  async function registerWorker(){if(!('serviceWorker'in navigator))throw new Error('Notifications are not supported on this browser.');return navigator.serviceWorker.register('sw.js',{scope:'./'})}
  async function enable(){try{if(!('Notification'in window)||!('PushManager'in window))throw new Error('Push notifications are not supported on this device/browser.');if(!managerSessionToken)throw new Error('Please sign in again before enabling notifications.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not granted.');const reg=await registerWorker();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes(VAPID_PUBLIC_KEY)});const j=sub.toJSON();const {data,error}=await db.rpc('push_save_subscription',{p_token:managerSessionToken,p_endpoint:j.endpoint,p_p256dh:j.keys.p256dh,p_auth:j.keys.auth,p_device_id:localStorage.getItem(DEVICE_KEY)||'',p_user_agent:navigator.userAgent});if(error)throw error;if(!data?.success)throw new Error(data?.message||'Unable to enable notifications.');alert('Notifications are enabled on this device.');updateEnableButton()}catch(e){alert(e.message)} }
  async function updateEnableButton(){const b=document.getElementById('enableTimesheetNotifications');if(!b)return;b.textContent=Notification?.permission==='granted'?'🔔 Notifications Enabled':'🔔 Enable Notifications'}
  function build(){
    const profileActions=document.querySelector('.my-profile-actions');if(profileActions&&!document.getElementById('enableTimesheetNotifications')){const b=document.createElement('button');b.id='enableTimesheetNotifications';b.type='button';b.className='enable-notifications-btn';b.textContent='🔔 Enable Notifications';profileActions.parentNode.insertBefore(b,profileActions);b.addEventListener('click',enable);updateEnableButton()}
    const managerActions=document.querySelector('.manager-menu-actions');if(!managerActions||document.getElementById('managerSendNotificationBtn'))return;const mb=document.createElement('button');mb.id='managerSendNotificationBtn';mb.type='button';mb.className='manager-send-notification';mb.textContent='🔔 Send Notification';managerActions.insertBefore(mb,managerActions.children[3]||null);
    const modal=document.createElement('div');modal.id='sendNotificationModal';modal.className='notification-modal no-print';modal.hidden=true;modal.innerHTML=`<div class="notification-backdrop" data-close-notification></div><section class="notification-dialog" role="dialog" aria-modal="true"><div class="notification-header"><div><h2>Send Notification</h2><p>Send a reminder to staff who have enabled notifications.</p></div><button type="button" id="closeNotificationModal">×</button></div><label class="notification-label">Recipients<select id="notificationRecipients"><option value="all">All active staff</option></select></label><label class="notification-label">Message<select id="notificationTemplate"><option value="Reminder: please enter your times for today.">Enter your times today</option><option value="Please check and update your timesheet when you get a chance.">Check/update your times</option><option value="Timesheets are due today. Please make sure your hours are complete.">Timesheets due today</option><option value="custom">Custom message</option></select></label><textarea id="notificationMessage" rows="4">Reminder: please enter your times for today.</textarea><div id="notificationStatus" class="notification-status">DEV notifications only — nothing will be sent to Production users.</div><button id="sendNotificationNow" class="notification-send" type="button">Send Notification</button></section>`;document.body.appendChild(modal);
    mb.addEventListener('click',open);document.getElementById('closeNotificationModal').addEventListener('click',close);modal.querySelector('[data-close-notification]').addEventListener('click',close);document.getElementById('notificationTemplate').addEventListener('change',e=>{if(e.target.value!=='custom')document.getElementById('notificationMessage').value=e.target.value;else document.getElementById('notificationMessage').focus()});document.getElementById('sendNotificationNow').addEventListener('click',send)
  }
  function close(){document.getElementById('sendNotificationModal').hidden=true;document.body.classList.remove('staff-modal-open')}
  async function open(){const allowed=await requireManagerSession();if(!allowed)return;closeManagerMenu();const select=document.getElementById('notificationRecipients');select.innerHTML='<option value="all">All active staff</option>'+staffMembers.filter(s=>s.active).map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');document.getElementById('sendNotificationModal').hidden=false;document.body.classList.add('staff-modal-open')}
  async function send(){const btn=document.getElementById('sendNotificationNow'),status=document.getElementById('notificationStatus'),recipient=document.getElementById('notificationRecipients').value,message=document.getElementById('notificationMessage').value.trim();if(!message){status.textContent='Enter a message first.';return}btn.disabled=true;status.textContent='Sending…';try{const response=await fetch(`${window.APP_CONFIG.supabaseUrl}/functions/v1/send-timesheet-notification`,{method:'POST',headers:{'Content-Type':'application/json','apikey':window.APP_CONFIG.supabaseKey},body:JSON.stringify({manager_token:managerSessionToken,title:'Staff Timesheet',body:message,target_staff_ids:recipient==='all'?[]:[recipient]})});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||'Unable to send notification.');status.textContent=result.delivered?`Sent successfully to ${result.recipients} staff member${result.recipients===1?'':'s'} (${result.delivered} device${result.delivered===1?'':'s'}).`:`No notifications sent. The selected staff have not enabled notifications yet.`}catch(e){status.textContent=`Unable to send: ${e.message}`}finally{btn.disabled=false}}
  css();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();
