(function(){
  const PROMOTION_URL=window.APP_CONFIG?.isDevelopment?'https://appsbysam.github.io/One7One-Shake-Draw/?dev=1':'https://appsbysam.github.io/One7One-Shake-Draw/';
  function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
  function fmt(v){if(!v)return '';return new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00`))}
  function addCss(){if(document.getElementById('promotionAdminCss'))return;const l=document.createElement('link');l.id='promotionAdminCss';l.rel='stylesheet';l.href=`promotion-admin.css?v=${encodeURIComponent(window.APP_CACHE_TOKEN||Date.now())}`;document.head.appendChild(l)}
  function build(){
    const actions=document.querySelector('.manager-menu-actions');if(!actions||document.getElementById('managerMenuPromotionBtn'))return;
    const b=document.createElement('button');b.id='managerMenuPromotionBtn';b.type='button';b.className='manager-menu-promotion';b.textContent='🎁 Promotion Access';actions.insertBefore(b,actions.children[2]||null);
    const wrap=document.createElement('div');wrap.id='promotionAdminModal';wrap.className='promotion-admin-modal no-print';wrap.hidden=true;wrap.innerHTML=`<div class="promotion-admin-backdrop" data-close-promotion></div><section class="promotion-admin-dialog" role="dialog" aria-modal="true" aria-labelledby="promotionAdminTitle"><div class="promotion-admin-header"><div><h2 id="promotionAdminTitle">Promotion Access</h2><p id="promotionWeek">Weekly protein shake draw</p></div><button id="promotionAdminClose" class="promotion-admin-close" type="button">×</button></div><div id="promotionStatus" class="promotion-admin-status">Ready</div><div class="promotion-admin-stats"><div class="promotion-admin-stat"><strong id="promotionEntryCount">0</strong><span>Entries this week</span></div><div class="promotion-admin-stat"><strong id="promotionCustomerCount">0</strong><span>Unique customers</span></div></div><div class="promotion-admin-draws"><button id="promotionSimBtn" class="promotion-sim-btn" type="button">Simulation Draw</button><button id="promotionRealBtn" class="promotion-real-btn" type="button">Generate Weekly Winner</button></div><button id="promotionQrBtn" class="promotion-qr-btn" type="button">▦ Show Weekly QR Code</button><div id="promotionQrPanel" class="promotion-qr-panel" hidden><h3>FREE PROTEIN SHAKE DRAW</h3><p>Scan to enter</p><img id="promotionQrImage" alt="QR code for One7One free protein shake draw"><strong id="promotionQrWeek"></strong><small>${window.APP_CONFIG?.isDevelopment?'DEV QR — test entries are saved only to the DEV promotion database.':'This QR code opens the customer entry form.'}</small></div><div id="promotionResult" class="promotion-admin-result" hidden></div><section class="promotion-admin-section"><h3>Current Entries</h3><div id="promotionEntries" class="promotion-entry-list"></div></section><section class="promotion-admin-section"><h3>Winner History</h3><div id="promotionHistory" class="promotion-history-list"></div></section></section>`;document.body.appendChild(wrap);
    b.addEventListener('click',open);document.getElementById('promotionAdminClose').addEventListener('click',close);wrap.querySelector('[data-close-promotion]').addEventListener('click',close);document.getElementById('promotionSimBtn').addEventListener('click',simulate);document.getElementById('promotionRealBtn').addEventListener('click',drawReal);document.getElementById('promotionQrBtn').addEventListener('click',toggleQr)
  }
  let data=null;
  function status(t,error=false){const e=document.getElementById('promotionStatus');e.textContent=t;e.style.background=error?'#fff0f0':'#edf7ef';e.style.color=error?'#9c1e1e':'#17652a'}
  async function rpc(name,args){const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data}
  async function open(){const allowed=await requireManagerSession();if(!allowed)return;closeManagerMenu();document.getElementById('promotionAdminModal').hidden=false;document.body.classList.add('staff-modal-open');await load()}
  function close(){document.getElementById('promotionAdminModal').hidden=true;document.body.classList.remove('staff-modal-open')}
  function toggleQr(){const p=document.getElementById('promotionQrPanel'),btn=document.getElementById('promotionQrBtn');if(p.hidden){document.getElementById('promotionQrWeek').textContent=data?.week_end?`Entries for week ending ${fmt(data.week_end)}`:'Current weekly draw';document.getElementById('promotionQrImage').src=`https://quickchart.io/qr?size=320&margin=2&text=${encodeURIComponent(PROMOTION_URL)}`;p.hidden=false;btn.textContent='▦ Hide Weekly QR Code'}else{p.hidden=true;btn.textContent='▦ Show Weekly QR Code'}}
  async function load(){status('Loading promotion entries…');try{data=await rpc('promotion_admin_dashboard',{p_token:managerSessionToken});if(!data?.success)throw new Error(data?.message||'Manager session has expired.');document.getElementById('promotionWeek').textContent=`Week ${fmt(data.week_start)} – ${fmt(data.week_end)}`;document.getElementById('promotionEntryCount').textContent=data.entry_count||0;document.getElementById('promotionCustomerCount').textContent=data.unique_customers||0;const entries=data.entries||[];document.getElementById('promotionEntries').innerHTML=entries.length?entries.map(e=>`<article class="promotion-entry"><div><strong>${esc(e.full_name)}</strong><span>${esc(e.phone)}</span></div><time>${fmt(e.entry_date)}</time></article>`).join(''):'<div class="promotion-empty">No entries yet this week.</div>';const draws=data.draws||[];document.getElementById('promotionHistory').innerHTML=draws.length?draws.map(d=>`<article class="promotion-history"><div><strong>🏆 ${esc(d.winner_name)}</strong><span>${esc(d.winner_phone)}</span></div><time>Week ending ${fmt(d.week_end)}</time></article>`).join(''):'<div class="promotion-empty">No completed draws yet.</div>';const already=draws.some(d=>d.week_start===data.week_start);const real=document.getElementById('promotionRealBtn');real.disabled=already||!entries.length;real.textContent=already?'Winner Already Generated':'Generate Weekly Winner';document.getElementById('promotionSimBtn').disabled=!entries.length;status(window.APP_CONFIG.isDevelopment?'DEV test data loaded. Simulation is safe.':'Live promotion data loaded.')}catch(e){status(`Unable to load promotion: ${e.message}`,true)}}
  function simulate(){const entries=data?.entries||[];if(!entries.length)return;const winner=entries[Math.floor(Math.random()*entries.length)];const r=document.getElementById('promotionResult');r.hidden=false;r.className='promotion-admin-result';r.innerHTML=`SIMULATION ONLY — Would select: <strong>${esc(winner.full_name)}</strong> — ${esc(winner.phone)}<br><small>Nothing was written to the database.</small>`}
  async function drawReal(){const ok=confirm(window.APP_CONFIG.isDevelopment?'This is DEV. Generate a test winner in the DEV database?':'Generate and permanently record this week’s winner? This cannot be undone from the app.');if(!ok)return;const b=document.getElementById('promotionRealBtn');b.disabled=true;status('Generating winner…');try{const result=await rpc('promotion_draw_winner',{p_token:managerSessionToken});if(!result?.success)throw new Error(result?.message||'Unable to generate winner.');const r=document.getElementById('promotionResult');r.hidden=false;r.className='promotion-admin-result is-real';r.innerHTML=`🏆 Winner: <strong>${esc(result.winner_name)}</strong> — ${esc(result.winner_phone)}`;await load()}catch(e){status(e.message,true);b.disabled=false}}
  addCss();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();
